/*
MLD :

CLIENT(*Num_Client*, Nom, Adresse)
ACCIDENT(*Num_Accident*, Date)
CONTRAT(*Num_Contrat*, Type, Date, Marque, Modele, Annee, #Num_Client)
CONCERNE(*#Num_Accident, #Num_Contrat*)

 */

/* CREATION DES TABLES */

CREATE TABLE  CLIENT
(
  Num_Client 	NUMBER	NOT NULL,
  Nom_Client VARCHAR2(50) NOT NULL,
  Adresse_Client	TEXT,
) TABLESPACE Data_Sc_Pise_1 ;

CREATE TABLE  ACCIDENT
(
  Num_Accident 	NUMBER	NOT NULL,
  Date_Accident	DATE NOT NULL,
) TABLESPACE Data_Sc_Pise_1 ;

CREATE TABLE  CONTRAT
(
  Num_Contrat 	NUMBER	NOT NULL,
  Type_Contrat	VARCHAR2(25) NOT NULL,
  Date_Contrat DATE NOT NULL,
  Marque_Vehicule VARCHAR2(25),
  Modele_Vehicule VARCHAR2(25),
  Annee_Vehicule NUMBER,
  Num_Client NUMBER NOT NULL,
) TABLESPACE Data_Sc_Pise_1 ;

CREATE TABLE  CONCERNE
(
  Num_Accident	NUMBER	NOT NULL,
  Num_Contrat	NUMBER NOT NULL,
) TABLESPACE Data_Sc_Pise_1 ;

/* AJOUT DES PK */

ALTER TABLE CLIENT ADD CONSTRAINT CLIENT_PK 
PRIMARY KEY (Num_Client) USING INDEX TABLESPACE Indx_Sc_Pise_1 ;

ALTER TABLE ACCIDENT ADD CONSTRAINT ACCIDENT_PK 
PRIMARY KEY (Num_Accident) USING INDEX TABLESPACE Indx_Sc_Pise_1 ;

ALTER TABLE CONTRAT ADD CONSTRAINT CONTRAT_PK 
PRIMARY KEY (Num_Contrat) USING INDEX TABLESPACE Indx_Sc_Pise_1 ;

ALTER TABLE CONCERNE ADD CONSTRAINT CONCERNE_PK 
PRIMARY KEY (Num_Accident, Num_Contrat) USING INDEX TABLESPACE Indx_Sc_Pise_1 ;

ALTER TABLE CONTRAT ADD CONSTRAINT CONTRAT_FK
FOREIGN KEY (Num_Client) REFERENCES CLIENT(Num_Client) ;

ALTER TABLE CONCERNE ADD CONSTRAINT CONCERNE_FK
FOREIGN KEY (Num_Accident) REFERENCES ACCIDENT(Num_Accident) ;

ALTER TABLE CONCERNE ADD CONSTRAINT CONCERNE_FK
FOREIGN KEY (Num_Contrat) REFERENCES CONTRAT(Num_Contrat) ;