SPOOL "C:\temp\log\or_exo9_dll.log"

connect chokri/motdepasse

CREATE TABLE DEPT(
NUMD NUMBER(2),
NOMD VARCHAR2(14) ,
LIEU VARCHAR2(13) 
) ;

CREATE TABLE EMP(
NUME INTEGER,
NOME VARCHAR2(10),
FONCTION VARCHAR2(15),
NUMS NUMBER(4),
EMBAUCHE DATE,
SALAIRE NUMBER(7,2),
COMM NUMBER(7,2),
NUMD NUMBER(2)
);

INSERT INTO DEPT VALUES(1, 'Droit', 'Creeil');
INSERT INTO DEPT VALUES(2, 'Commerce', 'Boston');
INSERT INTO EMP VALUES (1, 'Gava', 'President', NULL, TO_DATE('10/10/1979','dd/mm/YYYY'), 10000, NULL, NULL);
INSERT INTO EMP VALUES (2, 'Guimezanes', 'Doyen', 1, TO_DATE('01/10/2006','dd/mm/YYYY'), 5000, NULL, 1);
INSERT INTO EMP VALUES (3, 'Toto', 'Stagiaire', 1, TO_DATE('01/10/2006','dd/mm/YYYY'), 0, NULL, 1);
INSERT INTO EMP VALUES (4, 'Al-Capone', 'Commercial', 2, TO_DATE('01/10/2006','dd/mm/YYYY'), 5000, 100, 2);

commit ;

SPOOL OFF