spool "C:\temp\log\or_exo8_create_table.log"

/*
MLD :
U(NumU, NomU, VilleU)
P(NumP, NomP, Couleur, Poids)
F(NumF, NomF, Statut, VilleF)
PUF(NumP, NumU, NumF, Quantité)

 */
 
CONNECT chokri/motdepasse 

PROMPT '>> Création table U'
CREATE TABLE
  U (
    NumU NUMBER NOT NULL,
    NomU VARCHAR2 (50) NOT NULL,
    VilleU VARCHAR2 (50) NOT NULL
  ) TABLESPACE DATA_SC_PISE;

PROMPT '>> Création table P'
CREATE TABLE
  P (
    NumP NUMBER NOT NULL,
    NomP VARCHAR2 (50) NOT NULL,
    Couleur VARCHAR2 (20) NOT NULL,
    Poids NUMBER
  ) TABLESPACE DATA_SC_PISE;

PROMPT '>> Création table F'
CREATE TABLE
  F (
    NumF NUMBER NOT NULL,
    NomF VARCHAR2 (50) NOT NULL,
    Statut VARCHAR2 (50) NOT NULL,
    VilleF VARCHAR2 (50) NOT NULL
  ) TABLESPACE DATA_SC_PISE;

PROMPT '>> Création table PUF'
CREATE TABLE
  PUF (
    NumP NUMBER NOT NULL,
    NumU NUMBER NOT NULL,
    NumF NUMBER NOT NULL,
    Quantite NUMBER NOT NULL
  ) TABLESPACE DATA_SC_PISE;

PROMPT '>> Ajout des contraintes PK sur U'
ALTER TABLE U ADD CONSTRAINT NUMU_PK PRIMARY KEY (NumU) USING INDEX TABLESPACE Indx_Sc_Pise;

PROMPT '>> Ajout des contraintes PK sur P'
ALTER TABLE F ADD CONSTRAINT NUMF_PK PRIMARY KEY (NumF) USING INDEX TABLESPACE Indx_Sc_Pise;

PROMPT '>> Ajout des contraintes PK sur F'
ALTER TABLE P ADD CONSTRAINT NUMP_PK PRIMARY KEY (NumP) USING INDEX TABLESPACE Indx_Sc_Pise;

PROMPT '>> Ajout des contraintes PK sur PUF'
ALTER TABLE PUF ADD CONSTRAINT PUF_PK PRIMARY KEY (NumP, NumU, NumF) USING INDEX TABLESPACE Indx_Sc_Pise;

PROMPT '>> Ajout des contraintes FK sur PUF'
ALTER TABLE PUF ADD CONSTRAINT PUF_1_FK FOREIGN KEY (NumU) REFERENCES U (NumU);

PROMPT '>> Ajout des contraintes FK sur PUF'
ALTER TABLE PUF ADD CONSTRAINT PUF_2_FK FOREIGN KEY (NumP) REFERENCES P (NumP);

PROMPT '>> Ajout des contraintes FK sur PUF'
ALTER TABLE PUF ADD CONSTRAINT PUF_3_FK FOREIGN KEY (NumF) REFERENCES F (NumF);

DISCONNECT

spool off