SPOOL "C:\temp\log\or_exo10_dml.log"

host cls

connect SCOTT/tiger

PROMPT >> 1- Fonction Manager dans dept 20 et 30
SELECT EMP.EMPNO, EMP.ENAME, EMP.MGR, EMP.HIREDATE, EMP.SAL, EMP.COMM, DEPT.DEPTNO
FROM EMP
INNER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
WHERE UPPER(EMP.JOB) = 'MANAGER' AND DEPT.DEPTNO IN (20, 30) ;

PROMPT >> 2- Employes sauf manager embauche en 81
SELECT *
FROM EMP
WHERE UPPER(EMP.JOB) <> 'MANAGER' AND TO_CHAR(HIREDATE, 'yyyy') = '1981' ;

PROMPT >> 3-  Employes avec A et M dans nom
SELECT *
FROM EMP
WHERE (UPPER(ENAME) LIKE '%M%A%' OR UPPER(ENAME) LIKE '%A%M%') ;

PROMPT >> 4- Employes avec deux A dans nom
SELECT *
FROM EMP
WHERE UPPER(ENAME) LIKE '%A%A%' ;

PROMPT >> 5- Employes avec commission
SELECT *
FROM EMP
WHERE COMM IS NOT NULL ;

PROMPT >> 6- Employes tries par dept, job et embauche
SELECT ENAME, DEPTNO, JOB, HIREDATE 
FROM EMP
ORDER BY DEPTNO, JOB, HIREDATE DESC ;

PROMPT >> 7- Employes a DALLAS
SELECT *
FROM EMP
INNER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
WHERE UPPER(DEPT.LOC) = 'DALLAS' ;

PROMPT >> 8- Employes embauche avant leur manager
SELECT ENAME, HIREDATE
FROM EMP 
/*WHERE HIREDATE < ANY (
    SELECT HIREDATE
    FROM EMP
    WHERE EMPNO = MGR
);*/
--MGR est l'id du manager (EMPNO)
-- Comparer HIREDATE des employes ou EMPNO est le code MGR 

PROMPT >> 9- Employes embauche avant BLAKE
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE < (
    SELECT HIREDATE 
    FROM EMP 
    WHERE UPPER(ENAME) = 'BLAKE'
    ) ;

SPOOL OFF