SPOOL "C:\temp\log\exo6_req_select.log"

CONNECT chokri/motdepasse

PROMPT >> Jours avec taux de remise sup '10%' ?
SELECT LIBELLE_JOUR
FROM JOUR_TAUX_REMISE
WHERE TX_REMISE > 10 ;

PROMPT >> Eleves nes en 1986 ou en 1987 ?
SELECT NOM_ELEVE, PRENOM_ELEVE
FROM ELEVE
WHERE TO_CHAR(DATE_NAIS_ELEVE, 'YYYY') IN ('1986', '1987') ;

PROMPT >> Eleves nes en 1986 ou en 1987  et non Paris ?
SELECT NOM_ELEVE, PRENOM_ELEVE, ADR_VILLE_ELEVE
FROM ELEVE
WHERE TO_CHAR(DATE_NAIS_ELEVE, 'YYYY') IN ('1986', '1987') AND UPPER(ADR_VILLE_ELEVE) NOT LIKE '%PARIS%' ;

PROMPT >>Vehicules mis en service entre le '01/01/2001' et le '15/07/2002' ?
SELECT MODELE
FROM VEHICULE
WHERE DATE_MISE_SERV BETWEEN TO_DATE('01/01/2001', 'DD/MM/YYYY') AND TO_DATE('15/07/2002', 'DD/MM/YYYY') ;

PROMPT >> Eleves prenommes Pierre ou Eric ?
SELECT NOM_ELEVE, PRENOM_ELEVE
FROM ELEVE
WHERE LOWER(PRENOM_ELEVE) IN ('pierre', 'eric') ;

PROMPT >> Vehicules de marque Renault ?
SELECT *
FROM VEHICULE
WHERE LOWER(MODELE) LIKE '%renault%' ;

DISCONNECT

SPOOL off
