ALTER TABLE CATEGORIE ADD CONSTRAINT CATEGORIE_FK FOREIGN KEY (IDT_TYPE_OPE) REFERENCES TYPE_OPERATION (IDT_TYPE_OPE);

ALTER TABLE SOUS_CATEGORIE ADD CONSTRAINT SOUS_CATEGORIE_FK FOREIGN KEY (IDT_CATEGORIE) REFERENCES CATEGORIE (IDT_CATEGORIE);

ALTER TABLE ECRITURE ADD CONSTRAINT ECRITURE_MODE_REG_FK FOREIGN KEY (IDT_MODE_REG) REFERENCES MODE_REGLEMENT (IDT_MODE_REG);

ALTER TABLE ECRITURE ADD CONSTRAINT ECRITURE_STATUT_FK FOREIGN KEY (IDT_STATUT) REFERENCES STATUT (IDT_STATUT);

ALTER TABLE ECRITURE ADD CONSTRAINT ECRITURE_SS_CAT_FK FOREIGN KEY (IDT_SS_CATEGORIE) REFERENCES SOUS_CATEGORIE (IDT_SS_CATEGORIE);

COMMIT;