ALTER TABLE ECRITURE
ALTER COLUMN DATE_ECRITURE
SET
    NOT NULL,
ALTER COLUMN EXERCICE_COMPTABLE
SET
    NOT NULL,
ALTER COLUMN TTC
SET
    NOT NULL;

ALTER TABLE MODE_REGLEMENT
ALTER COLUMN LIBELLE_MODE_REG
SET
    NOT NULL;

ALTER TABLE STATUT
ALTER COLUMN LIBELLE_STATUT
SET
    NOT NULL;

ALTER TABLE CATEGORIE
ALTER COLUMN LIBELLE_CATEGORIE
SET
    NOT NULL;

ALTER TABLE SOUS_CATEGORIE
ALTER COLUMN LIBELLE_SS_CATEGORIE
SET
    NOT NULL;

COMMIT;