ALTER TABLE TYPE_OPERATION ADD CONSTRAINT TYPE_OPERATION_PK PRIMARY KEY (IDT_TYPE_OPE);

ALTER TABLE CATEGORIE ADD CONSTRAINT CATEGORIE_PK PRIMARY KEY (IDT_CATEGORIE);

ALTER TABLE SOUS_CATEGORIE ADD CONSTRAINT SOUS_CATEGORIE_PK PRIMARY KEY (IDT_SS_CATEGORIE);

ALTER TABLE MODE_REGLEMENT ADD CONSTRAINT MODE_REGLEMENT_PK PRIMARY KEY (IDT_MODE_REG);

ALTER TABLE STATUT ADD CONSTRAINT STATUT_PK PRIMARY KEY (IDT_STATUT);

ALTER TABLE ECRITURE ADD CONSTRAINT ECRITURE_PK PRIMARY KEY (NUMERO);

COMMIT;