DELETE FROM ECRITURE
WHERE
    LENGTH (NUMERO) = 0
    OR LENGTH (DT_ECRITURE) = 0
    --OR LENGTH (HT) = 0
    --OR LENGTH (TTC) = 0
    --OR LENGTH (TVA) = 0
    OR LENGTH (IDT_SS_CATEGORIE) = 0;

COMMIT;