SELECT
    TYPE_OPERATION.LIBELLE AS "Type Operation",
    COUNT(*) AS "Nombre",
    SUM(ECRITURE.HT) AS "Total HT",
    SUM(ECRITURE.TTC) AS "Total TTC"
FROM
    ECRITURE
    INNER JOIN SOUS_CATEGORIE ON ECRITURE.IDT_SS_CATEGORIE = SOUS_CATEGORIE.IDT_SS_CATEGORIE
    INNER JOIN CATEGORIE ON CATEGORIE.IDT_CATEGORIE = SOUS_CATEGORIE.IDT_CATEGORIE
    INNER JOIN TYPE_OPERATION ON TYPE_OPERATION.IDT_TYPE_OPE = CATEGORIE.IDT_TYPE_OPE
GROUP BY
    TYPE_OPERATION.LIBELLE;