SELECT
    AVG(TTC) AS "Montant TTC Moyen"
FROM
    ECRITURE
    INNER JOIN SOUS_CATEGORIE ON ECRITURE.IDT_SS_CATEGORIE = SOUS_CATEGORIE.IDT_SS_CATEGORIE
    INNER JOIN CATEGORIE ON CATEGORIE.IDT_CATEGORIE = SOUS_CATEGORIE.IDT_CATEGORIE
WHERE
    UPPER(LIBELLE_CATEGORIE) = 'FONCTIONNEMENT ENTREPRISE';