SELECT
    TYPE_OPERATION.LIBELLE AS "Type Operation",
    SUM(ECRITURE.HT) AS "Total HT"
FROM
    ECRITURE
    INNER JOIN SOUS_CATEGORIE ON ECRITURE.IDT_SS_CATEGORIE = SOUS_CATEGORIE.IDT_SS_CATEGORIE
    INNER JOIN CATEGORIE ON CATEGORIE.IDT_CATEGORIE = SOUS_CATEGORIE.IDT_CATEGORIE
    INNER JOIN TYPE_OPERATION ON TYPE_OPERATION.IDT_TYPE_OPE = CATEGORIE.IDT_TYPE_OPE
GROUP BY
    EXERCICE_COMPTABLE,
    TYPE_OPERATION.LIBELLE
HAVING
    EXERCICE_COMPTABLE = 2022;