-- MODIFICATION DES TYPES DE DONNEES
ALTER TABLE ECRITURE
ALTER COLUMN HT TYPE DECIMAL USING HT::decimal,
ALTER COLUMN TVA TYPE DECIMAL USING TVA::decimal,
ALTER COLUMN TTC TYPE DECIMAL USING TTC::decimal;

COMMIT ;