ALTER TABLE MODE_REGLEMENT
ALTER COLUMN IDT_MODE_REG TYPE INTEGER USING IDT_MODE_REG::INTEGER ;

ALTER TABLE STATUT
ALTER COLUMN IDT_STATUT TYPE INTEGER USING IDT_STATUT::INTEGER;

ALTER TABLE SOUS_CATEGORIE
ALTER COLUMN IDT_SS_CATEGORIE TYPE INTEGER USING IDT_SS_CATEGORIE::INTEGER;

COMMIT;
