-- MODIFICATION DES TYPES DE DONNEES
ALTER TABLE ECRITURE
ALTER COLUMN HT TYPE DECIMAL USING HT::numeric,
ALTER COLUMN TVA TYPE DECIMAL USING TVA::numeric,
ALTER COLUMN TTC TYPE DECIMAL USING TTC::numeric;

COMMIT ;