-- MODIFICATION DES TYPES DE DONNEES
ALTER TABLE ECRITURE
ALTER COLUMN IDT_MODE_REG TYPE INTEGER USING IDT_MODE_REG::INTEGER,
ALTER COLUMN IDT_STATUT TYPE INTEGER USING IDT_STATUT::INTEGER,
ALTER COLUMN IDT_SS_CATEGORIE TYPE INTEGER USING IDT_SS_CATEGORIE::INTEGER;

COMMIT;