UPDATE ECRITURE
SET EXERCICE_COMPTABLE = RIGHT(EXERCICE_COMPTABLE, 4)
WHERE LENGTH(EXERCICE_COMPTABLE) > 4 ;

ALTER TABLE ECRITURE 
ALTER COLUMN EXERCICE_COMPTABLE TYPE INTEGER USING EXERCICE_COMPTABLE::INTEGER ;

COMMIT;