/*
MODIFICATION DES TYPES DE DONNEES
 */
ALTER TABLE t_onetau
ALTER COLUMN codapp TYPE VARCHAR(3),
ALTER COLUMN coddev TYPE VARCHAR(3),
ALTER COLUMN numtra TYPE INTEGER USING numtra::integer,
ALTER COLUMN datval TYPE DATE USING datval::date,
ALTER COLUMN mntnom TYPE DECIMAL USING mntnom::numeric;

/*
CONTRAINTES DE CLES PRIMAIRES
*/

ALTER TABLE t_onetau
ADD PRIMARY KEY (codapp, numtra);

/*
CONTRAINTES DE CLES PRIMAIRES
*/

CREATE INDEX [IF NOT EXISTS] coddev_index
ON t_onetau(coddev);

COMMIT ;