/*
MODIFICATION DES TYPES DE DONNEES
 */
ALTER TABLE t_onetau
ALTER COLUMN codapp TYPE VARCHAR(3),
ALTER COLUMN coddev TYPE VARCHAR(3),
ALTER COLUMN numtra TYPE INTEGER,
ALTER COLUMN datval TYPE DATE,
ALTER COLUMN mntnom TYPE DECIMAL;

/*
CONTRAINTES DE CLES PRIMAIRES
 */

ALTER TABLE t_onetau
ADD PRIMARY KEY (codapp, numtra);

/*
CONTRAINTES DE CLES PRIMAIRES
 */

CREATE INDEX [IF NOT EXISTS] coddev_index
ON t_onetau(coddev);