# Liste des fichiers sources
SOURCE=calculp.c calcsp.c

# Liste des fichiers objets
OBJETS=calculp.o calcsp.o

calcul : $(OBJETS)
	cc -o calcul $(OBJETS)

calculp.o : calculp.c
	cc -c calculp.c

calcsp.o : calcsp.c
	cc -c calcsp.c

